name: Publish Package to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Determine Project Version
        id: set_version
        run: |
          PROJECT_VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')

          echo "Determined project version: $PROJECT_VERSION"
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> "$GITHUB_ENV"

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GRADLE_PUBLISH_TOKEN }}
          VERSION: ${{ env.PROJECT_VERSION }}
